2024-08-27 16:49:35,237 - INFO - Запуск бота...
2024-08-27 16:49:35,753 - INFO - Найдено 1 ссылок на странице https://example.com
2024-08-27 16:49:35,754 - INFO - Обновлено 1 новых ссылок.
2024-08-27 16:52:28,093 - INFO - Запуск бота...
2024-08-27 16:52:31,098 - INFO - Запуск бота...
2024-08-27 16:52:31,156 - INFO - Найдено 0 ссылок на странице https://school.kontur.ru/publications/byudzhetnyj-uchet
2024-08-27 16:52:31,156 - INFO - Обновлено 0 новых ссылок.
2024-08-27 16:52:31,399 - INFO - Ссылка отправлена в группу -1002171117029: https://www.iana.org/domains/example
2024-08-27 16:52:31,571 - INFO - Ссылка отправлена в группу -1002176227393: https://www.iana.org/domains/example
2024-08-27 16:52:31,679 - ERROR - Ошибка при отправке ссылки в группу -1004269879858: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
2024-08-27 16:55:03,802 - INFO - Запуск бота...
2024-08-27 16:55:06,720 - INFO - Запуск бота...
2024-08-27 16:55:06,759 - INFO - Найдено 0 ссылок на странице https://school.kontur.ru/publications
2024-08-27 16:55:06,759 - INFO - Обновлено 0 новых ссылок.
2024-08-27 16:56:13,246 - INFO - Запуск бота...
2024-08-27 16:56:16,396 - INFO - Запуск бота...
2024-08-27 16:56:16,435 - INFO - Найдено 0 ссылок на странице https://school.kontur.ru/publications/discipline-bukhuchet
2024-08-27 16:56:16,436 - INFO - Обновлено 0 новых ссылок.
2024-08-27 16:58:23,053 - INFO - Запуск бота...
2024-08-27 16:58:25,806 - INFO - Запуск бота...
2024-08-27 16:58:26,256 - INFO - Найдено 299 ссылок на странице https://glavkniga.ru/news
2024-08-27 16:58:26,300 - INFO - Обновлено 189 новых ссылок.
2024-08-27 17:22:00,131 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-27 17:22:19,192 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-27 18:17:38,106 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-27 18:51:45,158 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 04:12:02,880 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway
2024-08-28 04:12:02,880 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway

2024-08-28 04:12:03,226 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway
2024-08-28 04:12:03,226 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway

2024-08-28 04:12:03,782 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway
2024-08-28 04:12:03,782 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway

2024-08-28 04:12:29,998 - ERROR - Произошла ошибка: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2024-08-28 04:12:30,009 - INFO - Попытка переподключения через 30 секунд...
2024-08-28 04:13:00,011 - INFO - Запуск бота...
2024-08-28 04:58:26,456 - INFO - Найдено 299 ссылок на странице https://glavkniga.ru/news
2024-08-28 04:58:26,473 - INFO - Обновлено 3 новых ссылок.
2024-08-28 07:34:28,049 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 07:40:45,523 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 07:40:53,747 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 07:40:53,864 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 08:00:43,782 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 08:15:15,637 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 08:23:14,453 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 08:23:20,500 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 08:32:10,753 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 08:32:57,348 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 08:34:27,156 - ERROR - Ошибка при отправке в группу -1004269879858: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
2024-08-28 09:00:02,512 - INFO - Запуск бота...
2024-08-28 09:00:14,648 - INFO - Запуск бота...
2024-08-28 09:00:15,117 - INFO - Найдено 301 ссылок на странице https://glavkniga.ru/news
2024-08-28 09:00:15,118 - INFO - Ссылка отправлена в группу -1002171117029: https://glavkniga.ru/news/17840
2024-08-28 09:00:15,129 - INFO - Обновлено 114 новых ссылок.
2024-08-28 09:00:15,341 - INFO - Ссылка отправлена в группу -1002176227393: https://glavkniga.ru/news/17840
2024-08-28 09:00:15,439 - ERROR - Ошибка при отправке ссылки в группу -1004269879858: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
2024-08-28 09:06:57,783 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 09:20:53,761 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 09:22:03,135 - INFO - Запуск бота...
2024-08-28 09:22:03,401 - INFO - Ссылка отправлена в группу -1002171117029: https://glavkniga.ru/news/17854
2024-08-28 09:22:03,583 - INFO - Ссылка отправлена в группу -1002176227393: https://glavkniga.ru/news/17854
2024-08-28 09:22:03,594 - INFO - Найдено 304 ссылок на странице https://glavkniga.ru/news
2024-08-28 09:22:03,597 - INFO - Обновлено 114 новых ссылок.
2024-08-28 09:22:03,650 - ERROR - Ошибка при отправке ссылки в группу -1004269879858: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
2024-08-28 09:29:59,791 - INFO - Запуск бота...
2024-08-28 09:30:01,204 - INFO - Запуск бота...
2024-08-28 09:30:01,558 - INFO - Ссылка отправлена в группу -1002171117029: https://glavkniga.ru/news/17862
2024-08-28 09:30:01,577 - INFO - Найдено 304 ссылок на странице https://glavkniga.ru/news
2024-08-28 09:30:01,580 - INFO - Обновлено 113 новых ссылок.
2024-08-28 09:30:01,828 - INFO - Ссылка отправлена в группу -1002176227393: https://glavkniga.ru/news/17862
2024-08-28 09:30:01,976 - ERROR - Ошибка при отправке ссылки в группу -1004269879858: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
2024-08-28 10:06:06,002 - INFO - Запуск бота...
2024-08-28 10:06:18,304 - INFO - Запуск бота...
2024-08-28 10:06:18,638 - INFO - Ссылка отправлена в группу -1002171117029: https://glavkniga.ru/news/?week=32-2024
2024-08-28 10:06:18,742 - INFO - Найдено 304 ссылок на странице https://glavkniga.ru/news
2024-08-28 10:06:18,744 - INFO - Обновлено 113 новых ссылок.
2024-08-28 10:06:18,793 - INFO - Ссылка отправлена в группу -1002176227393: https://glavkniga.ru/news/?week=32-2024
2024-08-28 10:06:18,855 - ERROR - Ошибка при отправке ссылки в группу -1004269879858: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
2024-08-28 10:07:45,009 - INFO - Запуск бота...
2024-08-28 10:07:51,521 - INFO - Запуск бота...
2024-08-28 10:07:52,015 - INFO - Ссылка отправлена в группу -1002171117029: https://glavkniga.ru/news/filter
2024-08-28 10:07:52,027 - INFO - Найдено 304 ссылок на странице https://glavkniga.ru/news
2024-08-28 10:07:52,042 - INFO - Обновлено 113 новых ссылок.
2024-08-28 10:07:52,188 - INFO - Ссылка отправлена в группу -1002176227393: https://glavkniga.ru/news/filter
2024-08-28 10:07:52,274 - ERROR - Ошибка при отправке ссылки в группу -1004269879858: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
2024-08-28 10:08:09,877 - INFO - Запуск бота...
2024-08-28 10:08:11,662 - INFO - Запуск бота...
2024-08-28 10:08:12,019 - INFO - Ссылка отправлена в группу -1002171117029: https://glavkniga.ru/news/17877
2024-08-28 10:08:12,116 - INFO - Найдено 304 ссылок на странице https://glavkniga.ru/news
2024-08-28 10:08:12,118 - INFO - Обновлено 113 новых ссылок.
2024-08-28 10:08:12,161 - INFO - Ссылка отправлена в группу -1002176227393: https://glavkniga.ru/news/17877
2024-08-28 10:08:12,241 - ERROR - Ошибка при отправке ссылки в группу -1004269879858: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
2024-08-28 13:19:40,115 - INFO - Запуск бота...
2024-08-28 13:19:40,512 - INFO - Найдено 308 ссылок на странице https://glavkniga.ru/news
2024-08-28 13:19:40,581 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 13:19:40,965 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 13:19:40,966 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 13:19:40,983 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 13:22:38,058 - ERROR - Произошла ошибка: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-08-28 13:22:38,058 - INFO - Попытка переподключения через 30 секунд...
2024-08-28 13:23:08,069 - INFO - Запуск бота...
2024-08-28 13:24:57,462 - INFO - Запуск бота...
